CString pStr;
pStr="Win85 is made available under the MIT License.\r\n\
\r\n\
Copyright (c) 2000-2013 George Manolaros\r\n\
\r\n\
http://pythagoras.physics.upatras.gr/~gmanol\r\n\
gmanol@physics.upatras.gr\r\n\
\r\n\
Permission is hereby granted, free of charge, to any person\r\n\
obtaining a copy of this software and associated documentation\r\n\
files (the \"Software\"), to deal in the Software without\r\n\
restriction, including without limitation the rights to use,\r\n\
copy, modify, merge, publish, distribute, sublicense, and/or\r\n\
sell copies of the Software, and to permit persons to whom\r\n\
the Software is furnished to do so, subject to the\r\n\
following conditions:\r\n\
\r\n\
The above copyright notice and this permission notice\r\n\
shall be included in all copies or substantial portions\r\n\
of the Software.\r\n\
\r\n\
THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY\r\n\
OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT\r\n\
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\r\n\
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO\r\n\
EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE\r\n\
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,\r\n\
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,\r\n\
ARISING FROM, OUT OF OR IN CONNECTION WITH THE\r\n\
SOFTWARE OR THE USE OR OTHER DEALINGS IN\r\n\
THE SOFTWARE.\r\n\
\r\n";